- name: Restart the Kibana service
  service:
    name: kibana
    state: restarted
  listen: event_restart_prometheus

- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload